### ISSUE TITLE
APK not installing on some Android (2.3)

### ISSUE THREAD

**Issue by MikeLockz** [colorado-code-for-communities/androidtracks#8]
Not sure what the cause of the issue is. App errors need to get fixed first.

Android seems to have problem installing from APK if the package is already present on the system. -|V|

Replicated the same issue and resolution on Nexus 7 running 4.2 Jellybean. - |V|

**Comment by mberson** [comment]
Building latest codebase in Android Studio with build target Google APIs (4.2.2).
Build fails because it can't find the maps package.
For some reason, had to open Project Structure and specify Google APIs a second time.
Build successful.
Opened APK with "Verify and Install service" on Droid X (2.3 Gingerbread).
Installation failed.
Opened APK with "Package installer".
Installation failed.
Rebuilt package with fresh private key.
Installation still failed with both services.
Uninstalled previous package, and retried APK.
Install successful.
